### ISSUE TITLE
Add code documentation

### ISSUE THREAD

**Issue by Demfier** [kaustubhhiware/c0derunR#11]
Adding docstrings to the modules will surely help in better understanding of what is going on inside of it.
We have a lot of undocumented code in coyote module as well as in our js files.

For python, follow the format:
```python
def function(param1):
    """
    Parameters:
    param1 [type] => its description
    --------------------------------------------------
    Returns:
    output1 [type] => its description
    """

    # Logic..

    return(output1)
```

For javascript:
```javascript
function name(param1) {
    /*
    @param {Type} param1 - description
    @returns {Type} output1 - description
    */

    // Logic..
    
   return output
}
```

**Comment by 142ayushkumar** [comment]
Can you assign me this issue?

**Comment by Demfier** [comment]
@142ayushkumar - You can start working on this one. In the meanwhile we will assign you this issue.
Also, don't forget to go through [CONTRIBUTING.md](https://github.com/kaustubhhiware/c0derunR/tree/master/CONTRIBUTING.md) before making a PR. It will help you stay away from minor distracting nuisances.

Good Luck :smile: !

**Comment by kaustubhhiware** [comment]
@142ayushkumar accept the collaborator request, I'll assign you soon after.

**Comment by kaustubhhiware** [comment]
Also mention what work you have done so far, and any difficulties you've had

**Comment by 142ayushkumar** [comment]
Unable to understand home function in views.py

**Comment by Demfier** [comment]
Well, if it isn't the pith of the entire backend :sweat_smile: . There are a lot of things happening inside the `home` method.

[L#27-43](https://github.com/kaustubhhiware/c0derunR/blob/master/coyote/views.py#L27-L43):
- Checks if the there is a `POST` ajax request from the frontend.
- If it isn't, that means it is simply `get` request to the home page and we render `init.html`
- If it is, then extracts relevant fields like `lang` etc from the `request` object and prepares the payload to be sent to the Hackerearth API. Basically it takes in the code to be compiled.

[L#45-53](https://github.com/kaustubhhiware/c0derunR/blob/master/coyote/views.py#L45-L53):
- Sends prepared payload to the hackerearth api.
- The API then returns the compiled code result (as json)

[L#54-66](https://github.com/kaustubhhiware/c0derunR/blob/master/coyote/views.py#L54-L66)
- If the code doesn't compile, we extract the key words from the error message and build `key_words`

[L#68-82](https://github.com/kaustubhhiware/c0derunR/blob/master/coyote/views.py#L68-L82)
- We make a google search of the key words
- With some regex matching and filtering, we get the hyperlinks and description of the results.
- Finally, we store them in `current_json['debug_urls']` and `current_json['descriptions']` and return to the frontend. These are the very links one sees when he/she clicks on the `DEBUG` button.

Hope you understand the purpose of `home` now.

Cheers!
