### ISSUE TITLE
Better HTMLviewer UI

### ISSUE THREAD

**Issue by Demfier** [kaustubhhiware/c0derunR#12]
The [HTMLviewer](http://c0derunr.herokuapp.com/htmlviewer) currently doesn't quite match with the rest of the [c0derunR](http://c0derunr.herokuapp.com/) UI. It would be nice if it could also be taken care of.

**Comment by 142ayushkumar** [comment]
Can you assign me this issue?

**Comment by 142ayushkumar** [comment]
@Demfier @kaustubhhiware 
Check if any of the following is good enough?
![image](https://user-images.githubusercontent.com/23264605/34461417-5742dd3e-ee4f-11e7-81dd-7b4f441c487f.png)
and 
![image](https://user-images.githubusercontent.com/23264605/34461420-7500c48a-ee4f-11e7-885e-d3a88ec8ffac.png)

**Comment by kaustubhhiware** [comment]
The second one looks perfect to me, what do you say @Demfier ?

**Comment by Demfier** [comment]
Yup, second one for sure. Good going @142ayushkumar

**Comment by kaustubhhiware** [comment]
@142ayushkumar submit a PR now.
