### ISSUE TITLE
Fix links on HTMLviewer

### ISSUE THREAD

**Issue by kaustubhhiware** [kaustubhhiware/c0derunR#13]
The fork link on HTMLViewer is incorrect: http://c0derunr.herokuapp.com/htmlviewer.

Also, the icon is not set.

Need to correct it to this repository

**Comment by vishalol** [comment]
As far as I understand this issue,does this require rendering some other page instead of the default one which is showing up right now ?

**Comment by kaustubhhiware** [comment]
No, this is really simple. You need to just change a href tag on the HTMLviewer to point to this repository.

**Comment by vishalol** [comment]
https://github.com/kaustubhhiware/c0derunR/pull/21  please review this

**Comment by kaustubhhiware** [comment]
@VishalCR7 DO NOT SUBMIT a PR before December 1. Please see my comments on your PR #21

**Comment by vishalol** [comment]
@kaustubhhiware can you please explain what we are supposed to do till then?

**Comment by kaustubhhiware** [comment]
That is supposed to be a period for students to register by December 1 and coding period starts only then.
Please [RTFM](https://en.wikipedia.org/wiki/RTFM) before making PR's. : http://kwoc.kossiitkgp.in/#timeline

**Comment by Demfier** [comment]
@VishalCR7 - We appreciate your enthusiasm to contribute :smile: 
You can have a look at other issues, have a discussion on the ones you find interesting and you can start working on them before hand. After all, Rome wasn't built in a day!
However, kindly submit the PRs only after December 1. We would be able to merge your PRs only after that.

Cheers!

**Comment by imVivekGupta** [comment]
I would like to fix the issue.

**Comment by kaustubhhiware** [comment]
We're sorry @imVivekGupta but @VishalCR7 had already submitted a P.R for this.
It would be incorrect to discard his PR.

We like your enthusiasm to contribute, so please also see other issues. They have been tagged accordingly.

**Comment by 142ayushkumar** [comment]
I will like to resolve this issue.

**Comment by kaustubhhiware** [comment]
Get working @142ayushkumar , you don't have much time :sweat_smile:
