### ISSUE TITLE
Fix Hello World template for a few languages

### ISSUE THREAD

**Issue by kofls** [kaustubhhiware/c0derunR#16]
A few languages have syntax errors in the hello world template. Should be a simple fix. 

Currently, the languages that need fixing:
- [ ] C# 
- [ ] Haskell
- [ ] Java
- [ ] Lisp
- [ ] Objective-C 
- [ ] PHP

**Comment by mikeesto** [comment]
Hi. I can work on this. I've noticed that there is also an issue with C that I will fix too.

**Comment by kaustubhhiware** [comment]
Thank you for your interest, @MichaelE1  😄 

I'll just assign you this issue now.
