### ISSUE TITLE
Add more languages in switcher

### ISSUE THREAD

**Issue by kaustubhhiware** [kaustubhhiware/c0derunR#22]
If any programming language is missing, which a significant amount of people using the website need.

This will also require creating the default code snippet for it.

You can know the supported languages by a simple lookup on hackerearth's API documentation.

**Comment by kurianbenoy** [comment]
How can I do so?

**Comment by kaustubhhiware** [comment]
Thanks for your interest @kurianbenoy .
I would request you to go through the code, this is really simple once you find where the current list of languages is mentioned in the code.
After that, to add the missing languages, you are to read up on hackerearth's API, seeing which language support they provide, and report that to us if you are working on something.

**Comment by kurianbenoy** [comment]
Thanksc @kaustubhhiware , I will do this . Can you assign me the issue?

**Comment by kaustubhhiware** [comment]
Closed in favour of #23.
