### ISSUE TITLE
Add snippets for new languages

### ISSUE THREAD

**Issue by kaustubhhiware** [kaustubhhiware/c0derunR#25]
In favour of #23, some new languages were added. New snippets are required for the same
- [x] CPP14
- [x] Erlang
- [x] Javascript
- [x] Javascript (node)
- [x] Kotlin
- [x] Octave
- [x] Python3
- [x] Rust
- [x] Swift
- [x] Visual basic

The snippet for each language must contain a simple hello world printing line, and commented instructions for how to take input, if the language supports.

**Comment by sunitharavi9** [comment]
Hey! Can you assign me this?

**Comment by kaustubhhiware** [comment]
Sure !
I'll add you as a collaborator. Assign this issue to yourself.
Pease go through [CONTRIBUTING.md](https://github.com/kaustubhhiware/c0derunR/blob/master/CONTRIBUTING.md) before starting your work.
