### ISSUE TITLE
Update Hacker earth api version

### ISSUE THREAD

**Issue by Demfier** [kaustubhhiware/c0derunR#3]

**Comment by kaustubhhiware** [comment]
The API version was already v3. v2 was discontinued at the end of August 2017.

As of today, seems our token has expired, so will be updating soon.

**Comment by kaustubhhiware** [comment]
Ping @142ayushkumar and @Demfier 
![image](https://user-images.githubusercontent.com/11318551/34035254-7e27a376-e1a7-11e7-83dd-be72735d7f5b.png)


I will be updating the token soon, so that should take care of it.

**Comment by Demfier** [comment]
Okay, cool
ᐧ

**Comment by kurianbenoy** [comment]
@kaustubhhiware are you going to work on this issue?

**Comment by kaustubhhiware** [comment]
I'm working on this at the moment. If you're interested in taking this up, I don't mind. Let us know accordingly here.

**Comment by kurianbenoy** [comment]
Ok @kaustubhhiware  you can continue work ! I was just excited to contribute again

**Comment by kaustubhhiware** [comment]
Since this is now a KWoC project, I think a KWoC applicant can do this.
I am not able to give it the attention it requires at the moment, so if @kurianbenoy is interested in this, you can assign it to yourself.

Unassigning self.

**Comment by kurianbenoy** [comment]
@kaustubhhiware  , I was willing to work on it, but as I am not so experienced,I can't guarnte the attention it really requires and it takes time to do something. 

I will assign this issue myself when I really start working on this .

**Comment by 142ayushkumar** [comment]
#36

**Comment by kaustubhhiware** [comment]
@142ayushkumar For future PR's, you shouldn't close issues like that.

In your P.R, you should write "resolves #3" or "closes #3", that automatically closes issue. I've been doing this for a while so you didn't notice.
