### ISSUE TITLE
Setup a beta link for c0derunR

### ISSUE THREAD

**Issue by Demfier** [kaustubhhiware/c0derunR#33]
It would be nice if we could have a beta version of c0derunR deployed.
So we don't have to "guess" what is going to happen when we merge a PR or add a new feature.
It would compensate for the lack of tests in the backend and would save us from the pain to test it locally everytime.

**Comment by 142ayushkumar** [comment]
Do we have to create a heroku pipeline for this?

**Comment by 142ayushkumar** [comment]
?

**Comment by Demfier** [comment]
@142ayushkumar - Sorry for the delayed response. But don't worry @kaustubhhiware is going to take care of this one.

**Comment by kaustubhhiware** [comment]
Tested with #37, #38.
Auto-deploy works perfectly on every PR, just need to check `http://c0derunr-pr-38.herokuapp.com` or just `c0derunr-pr-38.herokuapp.com` instead of `https://c0derunr-pr-38.herokuapp.com` for every issue (issue number 38 in this example.)
